Bump all things
ilharp/sign-android-release pull request #5
Opened 2022-08-02 10:29 UTC by Goooler

2022-08-02 10:54 UTC, simon300000 approved these changes
lgtm

2022-08-02 10:56 UTC, Goooler commented
等下回去我把 ci 修好

2022-08-02 10:57 UTC, simon300000 requested changes
应该把每个改动分一个单独的pr

2022-08-03 17:32 UTC, Goooler commented
@ilharp

2022-08-03 17:48 UTC, ilharp requested changes
The same view as @simon300000. Divide your PR according to changes and resubmit. One single change in one PR.

2022-08-03 17:48 UTC, ilharp commented on .editorconfig
> -
`.editorconfig` should keep the same behavior as `.gitattributes`.

2022-08-03 17:48 UTC, ilharp commented on .github/workflows/build.yml
> +        java-version: '17'
According to [WhichJDK](https://whichjdk.com), [Adoptium Temurin](https://adoptium.net) should be the best choice. Why zulu?

2022-08-03 17:48 UTC, ilharp commented on gradle.properties
> +org.gradle.parallel=true
Please give explanations of these parameters separately. The target machine to run this build on is unknown, so we should not specify memory parameters.

2022-08-03 17:48 UTC, ilharp commented on settings.gradle.kts
> +        maven("https://maven.aliyun.com/repository/public")
Do not use mirror repository in public source code.

2022-08-03 17:48 UTC, ilharp commented on settings.gradle.kts
> +}
I didn't see the benefit of enabling `gradle-enterprise` on such a small project.

2022-08-03 17:48 UTC, closed without merging